extends Node

const PLAYER_SPEED := 7.0
const MOUSE_SENS := 0.002

const NULL_SPEED := 35.0
const NULL_MAX_DISTANCE := 60.0

const CHASER_SPEED := 3.0

const START_ENEMIES := 2
const START_TURRETS := 1

const SPIKE_SPEED := 6.2
const SPIKE_DASH_SPEED := 12.0
const SPIKE_DASH_TIME := 0.16
const SPIKE_DASH_COOLDOWN := 0.65

const EXCEPTION_SPEED := 4.6
const EXCEPTION_DASH_SPEED := 14.0
const EXCEPTION_DASH_TIME := 0.22
const EXCEPTION_DASH_COOLDOWN := 1.1
